# Generated by Django 3.0.4 on 2020-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('linkedin_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('git_link', models.URLField(blank=True)),
                ('education', models.TextField(max_length=2000)),
                ('experience', models.TextField()),
                ('skills', models.TextField(blank=True, max_length=1000)),
                ('interests', models.TextField(blank=True, max_length=1000)),
                ('awards_and_certifications', models.TextField(blank=True, max_length=2000)),
                ('url', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CV Profile',
                'verbose_name_plural': 'CV Profiles',
                'ordering': ['-created'],
            },
        ),
    ]
